language: node_js
node_js:
- stable
addons:
  code_climate:
    repo_token: 1f73b665e5b743d53dc86a47ced92b94c1116e8cc238a4dc908a3aa139a2f883
before_script:
- npm -g install browserstack-runner
script:
- browserstack-runner
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
env:
  secure: qda0BJ5r7SGOzSTYj8GNyQsuB9P2YTw4pgbOIO2jlbVEDl2ZVye0lDnOY0yTo6b2G3ybQ1aL2muQbRQzyNJVPQAOsJ/gbHfbTeqtfqGPPmkLrDip7wpC/Bi7t2YedRyQfiK4dR5YNehnx2NJRsJLj3BNyAKD2rk5ad7omCMfHgVAfNx/10XaqFceOxOItqhf+6Wog4++r7Q5fqqcOIzRLxdP2uMBbJtyKEEY02vRw7JvLtzFWT2JTueGueGbwLzoW23koJReF+hR/zi7dsxL4cTa2cgxTGzdrnY6Jlut+qoJVv5mu+P6WTLYJrz+rYgwD9uqfUrb8kOIVXJUBtIAVk7md+d+/Mx91Q2de1ui0JUHMHH9kSlNMbKXhP7WRN5beNCYYXsPyy7fbaFXCPZ/9SBWbE1XkkYos1ScGoibjCOebvUahyHmaaaY46ayCnzx4WHrVwp37GCRHNTXIRf26ajojJbHwUQZyExeHJMeinNcV0m76HC60yePh91MJwuNRCe3u6RnXTGwTNi6Y0a8kbWwdXe4cJCEVKAdEig1f0v4TZtvDirWZSOimsFMycc87pEn9aMc2QRyO6AGPBpqjHlk1RtOUT4/msvPQbgPIGOtsD84/Sq8oJ+3Uk27gZMbPtbR77NOWGmoJdValRD0PVeNrUzQ/thw2gAoousSchs=
