language: node_js
node_js:
  - "stable"
addons:
   code_climate:
       repo_token: 1f73b665e5b743d53dc86a47ced92b94c1116e8cc238a4dc908a3aa139a2f883
before_script:
  - npm -g install browserstack-runner
script:
  - browserstack-runner
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info